INSERT INTO CATEGORIA (nombre) VALUES
('Abarrotes'),
('Bebidas'),
('Snacks'),
('Lácteos'),
('Panadería'),
('Limpieza'),
('Higiene Personal'),
('Medicina Básica'),
('Dulces'),
('Útiles Escolares'),
('Cigarrillos'),
('Helados'),
('Condimentos'),
('Enlatados'),
('Frutas y Verduras');