DROP DATABASE db_ventas;

CREATE DATABASE db_ventas;
USE db_ventas;

CREATE TABLE CATEGORIA (
  idCategoria INT AUTO_INCREMENT PRIMARY KEY,

  nombre VARCHAR(50) NOT NULL,
  
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  UNIQUE (nombre)
);

CREATE TABLE MARCA (
  idMarca INT AUTO_INCREMENT PRIMARY KEY,

  nombre VARCHAR(50) NOT NULL,
  
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  UNIQUE (nombre)
);

CREATE TABLE PRODUCTO (
  idProducto INT AUTO_INCREMENT PRIMARY KEY,

  nombre VARCHAR(50) NOT NULL,
  precio DECIMAL(10,2) NOT NULL,
  stock INT NOT NULL,
  idCategoria INT NOT NULL,
  idMarca INT NOT NULL,

  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CHECK (precio > 0),
  CHECK (stock >= 0),
  FOREIGN KEY (idCategoria) REFERENCES CATEGORIA(idCategoria) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (idMarca) REFERENCES MARCA(idMarca) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE TIPO_CLIENTE (
  idTipoCliente INT AUTO_INCREMENT PRIMARY KEY,

  tipo ENUM('Natural', 'Juridico') NOT NULL DEFAULT 'Natural',

  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  UNIQUE (tipo)
);

CREATE TABLE CLIENTE (
  idCliente INT AUTO_INCREMENT PRIMARY KEY,

  nombre VARCHAR(50) NOT NULL,
  apellido VARCHAR(50) NOT NULL,
  direccion VARCHAR(100) NOT NULL,
  telefono VARCHAR(15) NOT NULL,
  email VARCHAR(50) NOT NULL,
  idTipoCliente INT NOT NULL,

  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  UNIQUE (email),
  FOREIGN KEY (idTipoCliente) REFERENCES TIPO_CLIENTE(idTipoCliente) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE CARGO (
  idCargo INT AUTO_INCREMENT PRIMARY KEY,

  nombre VARCHAR(50) NOT NULL,
  
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  UNIQUE (nombre)
);

CREATE TABLE EMPLEADO (
  idEmpleado INT AUTO_INCREMENT PRIMARY KEY,

  nombre VARCHAR(50) NOT NULL,
  apellido VARCHAR(50) NOT NULL,
  direccion VARCHAR(100) NOT NULL,
  telefono VARCHAR(15) NOT NULL,
  email VARCHAR(50) NOT NULL,
  idCargo INT NOT NULL,

  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  UNIQUE (email),
  FOREIGN KEY (idCargo) REFERENCES CARGO(idCargo) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE TIPO_PAGO (
  idTipoPago INT AUTO_INCREMENT PRIMARY KEY,

  tipo ENUM('Efectivo', 'Yape', 'Plin') NOT NULL DEFAULT 'Efectivo',

  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  UNIQUE (tipo)
);

CREATE TABLE VENTA (
  idVenta INT AUTO_INCREMENT PRIMARY KEY,

  total DECIMAL(10,2) DEFAULT 0.00,
  idCliente INT NOT NULL,
  idEmpleado INT NOT NULL,
  idTipoPago INT NOT NULL,

  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  FOREIGN KEY (idCliente) REFERENCES CLIENTE(idCliente) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (idEmpleado) REFERENCES EMPLEADO(idEmpleado) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (idTipoPago) REFERENCES TIPO_PAGO(idTipoPago) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE DETALLE_VENTA (
  idDetalleVenta INT AUTO_INCREMENT PRIMARY KEY,

  cantidad INT NOT NULL,
  idVenta INT NOT NULL,
  idProducto INT NOT NULL,

  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CHECK (cantidad > 0),
  UNIQUE (idVenta, idProducto),
  FOREIGN KEY (idVenta) REFERENCES VENTA(idVenta) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (idProducto) REFERENCES PRODUCTO(idProducto) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE BOLETA (
  idBoleta INT AUTO_INCREMENT PRIMARY KEY,

  numeroBoleta VARCHAR(20) NOT NULL DEFAULT '0',
  dni VARCHAR(15) NOT NULL,
  idVenta INT NOT NULL,

  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  UNIQUE (numeroBoleta),
  FOREIGN KEY (idVenta) REFERENCES VENTA(idVenta) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE FACTURA (
  idFactura INT AUTO_INCREMENT PRIMARY KEY,

  numeroFactura VARCHAR(20) NOT NULL DEFAULT '0',
  ruc VARCHAR(15) NOT NULL,
  idVenta INT NOT NULL,

  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  UNIQUE (numeroFactura),
  FOREIGN KEY (idVenta) REFERENCES VENTA(idVenta) ON DELETE RESTRICT ON UPDATE CASCADE
);